### PR TITLE
Fix MIUI (#4)

### LINKED ISSUE #4: Shadow position shift on MIUI
## Expected & Actual Behavior
Screenshot_icon

## Steps to Reproduce the Problem

Launch the sample app.

## Specifications

- Version: only tested 1.2.0 and 1.3.0, maybe all versions are affected
- Platform: MIUI 12

## Possible Method to Fix the Problem

Actually this is because MIUI draws the shadow for adaptive icons:
screenshot

However MIUI does not consider the bounds change, and always draws the shadow to left-top corner of the canvas. Then we need to avoid using `setBounds` function to set the offset [here](https://android.googlesource.com/platform/frameworks/libs/systemui/+/c3896b285c8c2d84899cdd269c4f76e49fda66ce/iconloaderlib/src/com/android/launcher3/icons/BaseIconFactory.java#298). `Canvas.translate` might be a good alternative.

```java
if (ATLEAST_OREO && icon instanceof AdaptiveIconDrawable) {
    int offset = Math.max((int) Math.ceil(BLUR_FACTOR * size),
            Math.round(size * (1 - scale) / 2 ));
    //icon.setBounds(offset, offset, size - offset, size - offset);
    icon.setBounds(0, 0, size - offset * 2, size - offset * 2);
    mCanvas.translate(offset, offset);
    icon.draw(mCanvas);
    mCanvas.translate(-offset, -offset);
}
```
Or we can totally drop the version check and use the else branch.

### PR DESCRIPTION
**Pull request by shatyuka**
Fixes #4 

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by zhanghai** [comment]
Thanks for bringing this to attention! However, this still doesn't look right, because iconloaderlib will be drawing the shadow again and icons will get double shadow on MIUI. Do you know a way to simply skip MIUI's shadow?

**Comment by shatyuka** [comment]
Yes, there are two shadows. However it looks much better than original shifted outline.
Turning off MIUI optimization in developer option will disable this feature, plus with many other useful features. It won't be a good solution.

**Comment by zhanghai** [comment]
If turning off MIUI optimization works, there should be something that's serving as a flag, and since we are doing things in our process (`AdaptiveIconDrawable` is a framework class), we may try to turn it off with reflection and get rid of the redundant MIUI shadow completely. Could you find out if there's such a flag?

**Comment by shatyuka** [comment]
Yes.
`private static volatile boolean sMiuiOptimizationEnable` in class `android.app.MiuiThemeHelper`.
And the public method:
```java
public static boolean isMiuiOptimizationEnabled() {
    return sMiuiOptimizationEnable;
}
```
I'll try it later.

**Comment by shatyuka** [comment]
Works with code:
```java
    public AppIconLoader(@Px int iconSize, boolean shrinkNonAdaptiveIcons,
                         @NonNull Context context) {
        try {
            Class<?> MiuiThemeHelper = context.getClassLoader().loadClass("android.app.MiuiThemeHelper");
            Field sMiuiOptimizationEnable = MiuiThemeHelper.getDeclaredField("sMiuiOptimizationEnable");
            sMiuiOptimizationEnable.setAccessible(true);
            sMiuiOptimizationEnable.set(null, false);
        } catch (Exception e) {
        }
        mIconSize = iconSize;
        mShrinkNonAdaptiveIcons = shrinkNonAdaptiveIcons;
        mContext = context;
    }
```

**Comment by zhanghai** [comment]
I see. Yes this may work, but I was expecting some flag under `AdaptiveIconDrawable` or similar. Upon second thought, turning off the entire MIUI optimization might have too much impact so I'd be careful with it, at least make it optional.

But before we go with turning off the entire optimization, I noticed that there is an `AdaptiveIconDrawableInjector.drawMiuiStroke()` method. Canvas drawing are typically done with a `Paint` object, and regular Android coding practice avoids allocating new objects on each draw call (to avoid GC pause), so I think there's some chance that there is a `Paint` field inside the `AdaptiveIconDrawableInjector`. Could you looked into the logic there and see what we can do, e.g. set the color of the `Paint` to transparent to make it a no-op? This would be a much safer approach for users of this library.

**Comment by shatyuka** [comment]
A simple way is overriding this method using reflection.

**Comment by zhanghai** [comment]
That sounds new to me. How would you "override" the static method `AdaptiveIconDrawableInjector.drawMiuiStroke()` with reflection? I thought one would need things like JVMTI or a hook framework to do that.

**Comment by shatyuka** [comment]
Oops, I don't know that. However, `drawMiuiStroke` update the Paint each time using `setStyle`, `setColor` and `setStrokeWidth`. Here I find an alternative to hide the shadow:
```java
    public AppIconLoader(@Px int iconSize, boolean shrinkNonAdaptiveIcons,
                         @NonNull Context context) {
        try {
            Class<?> AdaptiveIconDrawableInjector = context.getClassLoader().loadClass("android.graphics.drawable.AdaptiveIconDrawableInjector");
            Field MASK_PAINT = AdaptiveIconDrawableInjector.getDeclaredField("MASK_PAINT");
            MASK_PAINT.setAccessible(true);
            Paint paint = (Paint)MASK_PAINT.get(null);
            paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.DST));
        } catch (Exception e) {
        }
        mIconSize = iconSize;
        mShrinkNonAdaptiveIcons = shrinkNonAdaptiveIcons;
        mContext = context;
    }
```

**Comment by zhanghai** [comment]
Yeah, setting the transfer mode to to desitination sounds like a good fix for MIUI.

About the proposed code:

1. Could you use `Class.forName()` instead of `context.getClassLoader().loadClass()`?
2. Could you rename `AdaptiveIconDrawableInjector` to `adaptiveIconDrawableInjectorClass`, and `MASK_PAINT` to `maskPaintField`, to follow the naming convention of local variables?
2. Could you do it in a static initialization block, so that it is done only once?

**Comment by shatyuka** [comment]
Ok, please check the new commit.

**Comment by zhanghai** [comment]
LGTM. I would mvoe the code to a standalone class but I can do it myself.

Did you test again that this actually works? If so, I'll merge this and include it in the next release

**Comment by shatyuka** [comment]
Double checked. It works.

**Comment by zhanghai** [comment]
Merged, thanks for the contribution!

**Comment by zhanghai** [comment]
Released in v1.3.1 on Maven Central.

**Pull request merged**
